name: Build, Test, and Deploy ASP.NET Core 8 Application

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   path: my-repo
            
      # - name: Navitage to the solution directory
      #   run: cd my-repo  # Navigate into the solution directory

      - name: Print GITHUB_WORKSPACE
        run: echo  $GITHUB_WORKSPACE

      - name: List the workspace content
        run: ls -a

      # Set up .NET Core 8 SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the application
      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      # Run tests
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/stock-pot:latest StockPot/
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
          DOTNET_NOLOGO: true

      # Login to Docker Hub
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/stock-pot:latest
